# Generated by Django 5.1.2 on 2024-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('payload', models.CharField(max_length=200)),
            ],
        ),
    ]
